name: Stripe SDE Prep Journey
description: Game-style Kanban board tracking my progress towards Stripe SDE role 🚀
public: true

# Workflow settings
readme: ./README.md
template:
  name: basic_kanban
  description: Default Kanban template for tracking SDE prep
  owner: github
  version: 2

# Columns
columns:
  - name: 🎯 Backlog (Locked Quests)
  - name: 📝 To Do (Next Up)
  - name: ⚡ In Progress (Grinding XP)
  - name: 🔍 Review (Boss Checkpoint)
  - name: ✅ Done (Quest Completed)

# Cards (all start in Backlog)
cards:
  - note: "Level 0 - Setup: Install tools, choose programming language, setup environment"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 1 - Core Skills: Arrays, Strings, HashMaps, Linked Lists"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 2 - Algorithm Patterns: Two Pointers, Sliding Window, Dynamic Programming, Graphs"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 3 - Boss Fight 1: Solve DSA mock problems"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 4 - System Design: OOP, LLD, HLD, Payment API design"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 5 - Stripe World: Learn Stripe Products, Stripe API, mini project"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 6 - Boss Fight 2: System + Behavioral interviews prep"
    column: 🎯 Backlog (Locked Quests)

  - note: "Level 7 - Final Boss: Stripe Onsite Simulation"
    column: 🎯 Backlog (Locked Quests)
